import gradio as gr
import pandas as pd
import numpy as np
import pickle
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from fpdf import FPDF
import tempfile
import os

# ==============================
# LOAD DATA + MODEL
# ==============================

df = pd.read_csv("delhi_ncr_aqi_dataset.csv")

with open("aqi_prediction_model.pkl", "rb") as f:
    model = pickle.load(f)
with open("season_encoder.pkl", "rb") as f:
    le_season = pickle.load(f)
with open("dow_encoder.pkl", "rb") as f:
    le_dow = pickle.load(f)
with open("model_features.pkl", "rb") as f:
    features = pickle.load(f)

print("Model loaded successfully.")


# ==============================
# AQI CATEGORY + COLOR
# ==============================

def get_aqi_category(aqi):
    if aqi <= 50:
        return "Good", "#00e400"
    elif aqi <= 100:
        return "Satisfactory", "#92d050"
    elif aqi <= 200:
        return "Moderate", "#ffff00"
    elif aqi <= 300:
        return "Poor", "#ff7e00"
    elif aqi <= 400:
        return "Very Poor", "#ff0000"
    else:
        return "Severe", "#7e0023"


category_levels = {
    "Good": 1,
    "Satisfactory": 2,
    "Moderate": 3,
    "Poor": 4,
    "Very Poor": 5,
    "Severe": 6
}


# ==============================
# HEALTH IMPACT CALCULATOR
# ==============================

DELHI_POPULATION = 20_000_000

def get_health_impact(aqi):
    if aqi > 300:
        risk_percent = 100
    elif aqi > 200:
        risk_percent = 60
    elif aqi > 100:
        risk_percent = 30
    else:
        risk_percent = 10
    return int((risk_percent / 100) * DELHI_POPULATION)


# ==============================
# SIMULATION FUNCTION
# ==============================

def simulate(row, traffic_percent, construction, odd_even, crop_burning):
    row = row.copy()
    row["season_encoded"] = le_season.transform([row["season"]])[0]
    row["dow_encoded"] = le_dow.transform([row["day_of_week"]])[0]

    baseline_input = pd.DataFrame([row[features]])
    baseline_aqi = model.predict(baseline_input)[0]

    # Crop burning adds ~100 AQI points in Oct-Nov
    if crop_burning:
        baseline_aqi = min(baseline_aqi + 100, 500)

    # Odd-Even = effective 40% traffic reduction
    effective_traffic = traffic_percent
    if odd_even:
        effective_traffic = max(traffic_percent, 40)

    traffic_improvement = min((effective_traffic / 80) * 50, 50)

    if construction:
        total_improvement = traffic_improvement + 15 * (1 - traffic_improvement / 100)
        total_improvement = min(total_improvement, 60)
    else:
        total_improvement = traffic_improvement

    adjusted_aqi = baseline_aqi * (1 - total_improvement / 100)

    return round(baseline_aqi, 2), round(adjusted_aqi, 2), round(total_improvement, 2)


# ==============================
# TARGET AQI CALCULATOR
# ==============================

def calculate_required_reduction(row, target_aqi, construction, crop_burning):
    row = row.copy()
    row["season_encoded"] = le_season.transform([row["season"]])[0]
    row["dow_encoded"] = le_dow.transform([row["day_of_week"]])[0]

    baseline_input = pd.DataFrame([row[features]])
    baseline = model.predict(baseline_input)[0]

    if crop_burning:
        baseline = min(baseline + 100, 500)

    required_drop_percent = ((baseline - target_aqi) / baseline) * 100

    if required_drop_percent <= 0:
        return 0

    traffic_needed = (required_drop_percent / 50) * 80
    return round(max(0, min(traffic_needed, 80)), 1)


# ==============================
# PDF REPORT GENERATOR
# ==============================

def generate_pdf(season, traffic_reduction, construction_ban,
                 odd_even, crop_burning, month, hour, target_aqi,
                 baseline, final_aqi, improvement,
                 baseline_cat, final_cat, aqi_saved,
                 level_change, required_reduction,
                 people_at_risk_before, people_protected):

    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_fill_color(30, 30, 30)
    pdf.set_text_color(255, 255, 255)
    pdf.rect(0, 0, 210, 40, 'F')
    pdf.set_xy(10, 12)
    pdf.cell(0, 10, "Delhi Air Quality Policy Simulation Report", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_xy(10, 25)
    pdf.cell(0, 8, "Generated by Delhi Air Quality What-If Tool", ln=True)

    pdf.set_text_color(0, 0, 0)
    pdf.ln(15)

    # Section: Scenario Settings
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "  Scenario Settings", ln=True, fill=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 11)
    settings = [
        ("Season", season),
        ("Month", str(month)),
        ("Hour of Day", str(hour)),
        ("Traffic Reduction", f"{traffic_reduction}%"),
        ("Construction Ban", "Yes" if construction_ban else "No"),
        ("Odd-Even Scheme", "Active" if odd_even else "Not Active"),
        ("Crop Burning Effect", "Included" if crop_burning else "Not Included"),
    ]

    for label, value in settings:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(70, 8, f"  {label}:", ln=False)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, value, ln=True)

    pdf.ln(5)

    # Section: Results
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "  Simulation Results", ln=True, fill=True)
    pdf.ln(3)

    results = [
        ("Baseline AQI", f"{baseline:.0f} ({baseline_cat})"),
        ("Predicted AQI After Intervention", f"{final_aqi:.0f} ({final_cat})"),
        ("Total Improvement", f"{improvement:.1f}%"),
        ("AQI Points Saved", f"{aqi_saved:.0f}"),
        ("Category Level Shift", f"{level_change} levels improved"),
    ]

    for label, value in results:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(100, 8, f"  {label}:", ln=False)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, value, ln=True)

    pdf.ln(5)

    # Section: Health Impact
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "  Health Impact (Delhi Population: 20 Million)", ln=True, fill=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(100, 8, "  People at Risk (Before):", ln=False)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"{people_at_risk_before:,}", ln=True)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(100, 8, "  People Protected by Intervention:", ln=False)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"{people_protected:,}", ln=True)

    pdf.ln(5)

    # Section: Target Goal
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "  Target Goal Analysis", ln=True, fill=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(100, 8, "  Desired Target AQI:", ln=False)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, str(target_aqi), ln=True)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(100, 8, "  Required Traffic Reduction:", ln=False)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"{required_reduction}%", ln=True)

    pdf.ln(5)

    # Section: Evidence Base
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "  Evidence Base", ln=True, fill=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 10)
    evidence = [
        "- COVID Lockdown 2020: 80% traffic reduction led to 50% AQI improvement",
        "- Weekend Effect (2020-2025): 25% traffic reduction gives ~6% AQI improvement",
        "- Construction ban: ~15% reduction in PM10 (dust particles)",
        "- Odd-Even Scheme: Equivalent to ~40% traffic reduction on scheme days",
        "- Crop Burning: Adds ~100 AQI points during Oct-Nov season",
        "- Data Source: 6 years of data (2020-2025), 23 monitoring stations",
        "- Model Accuracy: R2 Score = 0.962 (96.2% accuracy)",
    ]

    for line in evidence:
        pdf.cell(0, 7, f"  {line}", ln=True)

    pdf.ln(5)

    # Footer
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 8,
             "Disclaimer: Predictions are based on historical patterns. "
             "Actual results may vary due to weather and external factors.",
             ln=True)

    # Save PDF
    tmp_file = tempfile.NamedTemporaryFile(
        delete=False, suffix=".pdf",
        prefix="Delhi_AQI_Report_"
    )
    pdf.output(tmp_file.name)

    return tmp_file.name


# ==============================
# MAIN PREDICTION FUNCTION
# ==============================

def predict_whatif(season, traffic_reduction, construction_ban,
                   odd_even, crop_burning, month, hour, target_aqi):

    season_map = {
        "Winter": "winter",
        "Summer": "summer",
        "Monsoon": "monsoon",
        "Post Monsoon": "post_monsoon"
    }

    selected_season = season_map[season]
    sample = df[df["season"] == selected_season].iloc[0].copy()
    sample["month"] = month
    sample["hour"] = hour

    baseline, final_aqi, improvement = simulate(
        sample, traffic_reduction, construction_ban, odd_even, crop_burning
    )

    baseline_cat, baseline_color = get_aqi_category(baseline)
    final_cat, final_color = get_aqi_category(final_aqi)

    aqi_saved = baseline - final_aqi
    level_change = category_levels[baseline_cat] - category_levels[final_cat]

    required_reduction = calculate_required_reduction(
        sample, target_aqi, construction_ban, crop_burning
    )

    people_at_risk_before = get_health_impact(baseline)
    people_at_risk_after = get_health_impact(final_aqi)
    people_protected = people_at_risk_before - people_at_risk_after

    # ==============================
    # HTML SUMMARY
    # ==============================

    interventions_list = []
    if traffic_reduction > 0:
        interventions_list.append(f"Traffic Reduction: {traffic_reduction}%")
    if odd_even:
        interventions_list.append("Odd-Even Scheme: Active")
    if construction_ban:
        interventions_list.append("Construction Ban: Yes")
    if crop_burning:
        interventions_list.append("Crop Burning Effect: Included")

    interventions_str = "<br>".join(interventions_list) if interventions_list else "None"

    summary = f"""
    <h3>INTERVENTION SUMMARY</h3>
    <hr>
    <b>Season:</b> {season}<br>
    <b>Interventions:</b><br>{interventions_str}<br><br>

    <b>Baseline AQI:</b>
    <span style='color:{baseline_color}; font-weight:bold; font-size:18px'>
        {baseline:.0f} ({baseline_cat})
    </span><br>

    <b>Predicted AQI:</b>
    <span style='color:{final_color}; font-weight:bold; font-size:18px'>
        {final_aqi:.0f} ({final_cat})
    </span><br><br>

    <b>Improvement:</b> {improvement:.1f}%<br><br>

    <div style='font-size:22px; font-weight:bold; color:#2E86C1'>
        AQI POINTS SAVED: {aqi_saved:.0f}
    </div>

    <hr>
    <b>Category Improvement:</b><br>
    <span style='color:{baseline_color}; font-weight:bold'>{baseline_cat}</span>
    →
    <span style='color:{final_color}; font-weight:bold'>{final_cat}</span><br>
    <b>Level Shift:</b> {level_change} Category Levels Improved

    <hr>
    <h4>HEALTH IMPACT</h4>
    <b>People at Risk Before:</b>
    {people_at_risk_before:,}<br>
    <b>People Protected:</b>
    <span style='color:#00cc44; font-weight:bold; font-size:16px'>
        {people_protected:,}
    </span><br><br>

    <hr>
    <h4>TARGET GOAL ANALYSIS</h4>
    To reach AQI <b>{target_aqi}</b>,<br>
    Required Traffic Reduction ≈ <b>{required_reduction}%</b>
    """

    # ==============================
    # MATPLOTLIB PLOTS
    # ==============================

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    axes[0].bar(
        ["Baseline", "After Intervention"],
        [baseline, final_aqi],
        color=[baseline_color, final_color],
        edgecolor='black',
        linewidth=0.5
    )
    axes[0].axhline(y=100, color='green', linestyle='--', alpha=0.5, label='Satisfactory')
    axes[0].axhline(y=200, color='orange', linestyle='--', alpha=0.5, label='Moderate')
    axes[0].axhline(y=300, color='red', linestyle='--', alpha=0.5, label='Poor')
    axes[0].set_ylim(0, 550)
    axes[0].set_title("Baseline vs Predicted AQI")
    axes[0].set_ylabel("AQI")
    axes[0].legend(fontsize=8)

    for bar, val in zip(axes[0].patches, [baseline, final_aqi]):
        axes[0].text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 5,
            f'{val:.0f}',
            ha='center', va='bottom',
            fontsize=12, fontweight='bold'
        )

    reductions = list(range(0, 81, 10))
    predicted_aqis = []

    for r in reductions:
        _, adj, _ = simulate(sample, r, construction_ban, odd_even, crop_burning)
        predicted_aqis.append(adj)

    axes[1].plot(reductions, predicted_aqis,
                 marker='o', color='steelblue',
                 linewidth=2, markersize=6,
                 label='Predicted AQI')
    axes[1].axhline(y=100, color='green', linestyle='--', alpha=0.5, label='Satisfactory')
    axes[1].axhline(y=200, color='orange', linestyle='--', alpha=0.5, label='Moderate')
    axes[1].axhline(y=300, color='red', linestyle='--', alpha=0.5, label='Poor')
    axes[1].axvline(x=traffic_reduction, color='purple',
                    linestyle=':', alpha=0.7,
                    label=f'Selected ({traffic_reduction}%)')
    axes[1].set_xlabel("Traffic Reduction (%)")
    axes[1].set_ylabel("Predicted AQI")
    axes[1].set_title("AQI vs Traffic Reduction")
    axes[1].legend(fontsize=8)

    plt.tight_layout()

    # ==============================
    # PLOTLY GAUGE
    # ==============================

    gauge = go.Figure(go.Indicator(
        mode="gauge+number",
        value=final_aqi,
        title={'text': "Predicted AQI"},
        gauge={
            'axis': {'range': [0, 500]},
            'bar': {'color': final_color},
            'steps': [
                {'range': [0, 50],    'color': "#00e400"},
                {'range': [50, 100],  'color': "#92d050"},
                {'range': [100, 200], 'color': "#ffff00"},
                {'range': [200, 300], 'color': "#ff7e00"},
                {'range': [300, 400], 'color': "#ff0000"},
                {'range': [400, 500], 'color': "#7e0023"},
            ],
        }
    ))

    # ==============================
    # GENERATE PDF
    # ==============================

    pdf_path = generate_pdf(
        season, traffic_reduction, construction_ban,
        odd_even, crop_burning, month, hour, target_aqi,
        baseline, final_aqi, improvement,
        baseline_cat, final_cat, aqi_saved,
        level_change, required_reduction,
        people_at_risk_before, people_protected
    )

    return summary, fig, gauge, pdf_path


# ==============================
# GRADIO UI
# ==============================

with gr.Blocks(title="Delhi Air Quality What-If Tool") as app:

    gr.Markdown("""
    # Delhi Air Quality What-If Tool
    ### Test how interventions improve air quality
    Built using 6 years of historical data (2020-2025)
    """)

    with gr.Row():

        with gr.Column(scale=1):

            season = gr.Dropdown(
                ["Winter", "Summer", "Monsoon", "Post Monsoon"],
                value="Winter",
                label="Select Season"
            )

            month = gr.Slider(1, 12, value=12, step=1, label="Month")
            hour = gr.Slider(0, 23, value=9, step=1, label="Hour")

            gr.Markdown("### Interventions")

            traffic_reduction = gr.Slider(
                0, 80, value=30, step=10,
                label="Traffic Reduction (%)"
            )

            construction_ban = gr.Checkbox(
                label="Apply Construction Ban (+15%)",
                value=False
            )

            odd_even = gr.Checkbox(
                label="Odd-Even Scheme (40% traffic reduction)",
                value=False
            )

            crop_burning = gr.Checkbox(
                label="Include Crop Burning Effect (+100 AQI)",
                value=False
            )

            gr.Markdown("### Target AQI Goal")

            target_aqi = gr.Slider(
                50, 400, value=150, step=10,
                label="Desired Target AQI"
            )

            run_btn = gr.Button("Run Simulation", variant="primary")

        with gr.Column(scale=2):

            output_text = gr.HTML(label="Results")

            with gr.Row():
                output_plot = gr.Plot(label="AQI Charts")

            with gr.Row():
                output_gauge = gr.Plot(label="AQI Gauge Meter")

            with gr.Row():
                output_pdf = gr.File(label="Download Policy Report (PDF)")

    run_btn.click(
        fn=predict_whatif,
        inputs=[
            season, traffic_reduction, construction_ban,
            odd_even, crop_burning, month, hour, target_aqi
        ],
        outputs=[output_text, output_plot, output_gauge, output_pdf]
    )

app.launch(share=True)